create table BatchUpload (
    syskey bigint not null primary key,
    createddate datetime,
    modifieddate datetime,
    userid nvarchar(50),
    username nvarchar(50),
    recordstatus SMALLINT default 1,
    UploadedDate datetime,
    ApprovedDate datetime,
    SubmittedDate datetime,
    VerifiedDate datetime,
    ByUserID nvarchar(50),
    UploadedRecords int,
    FileURL text,
    FileName text,
    BatchRefCode nvarchar(50),
    BatchNo bigint NOT NULL IDENTITY(1,1),
    PartnerSysKey bigint,
    PISysKey bigint,
    PaymentStatus SMALLINT default 0,
    VoidStatus SMALLINT default 1,
    centerid nvarchar(50),
    initserialno int,
    ErrorFileURL text,
    ErrorLogURL text,
    AttachmentURL1 text,
    AttachmentURL2 text,
    AttachmentURL3 text,
    AttachmentURL4 text,
    AttachmentURL5 text,
    AttachmentURL6 text,
    AttachmentURL7 text,
    AttachmentURL8 text,
    AttachmentURL9 text,
    AttachmentURL10 text,
    recipientsaved int default 0,
    validcount int default 0,
    invalidcount int default 0,
    isblankcard int default 0,
    duration nvarchar(255) default '0s',
    Remark nvarchar(255),
    t1 nvarchar(255),
    t2 nvarchar(255),
    t3 nvarchar(255),
    t4 nvarchar(255),
    t5 nvarchar(255),
    t6 nvarchar(255),
    t7 nvarchar(255),
    t8 nvarchar(255),
    t9 nvarchar(255),
    t10 nvarchar(255),
    n1 numeric(18, 2),
    n2 numeric(18, 2),
    n3 numeric(18, 2),
    n4 numeric(18, 2), 
    n5 numeric(18, 2),
    n6 numeric(18, 2),
    n7 numeric(18, 2),
    n8 numeric(18, 2),
    n9 numeric(18, 2), 
    n10 numeric(18, 2),
)