create table PartnerUser (
    syskey bigint not null primary key,
    createddate datetime,
    modifieddate datetime,
    userid nvarchar(50),
    username nvarchar(50),
    recordstatus SMALLINT default 1,
    remark nvarchar(255),
    role nvarchar(255),
    dvrsuserid bigint IDENTITY(100,1),
    dvrsusername nvarchar(50),
    partnersyskey bigint not null,
    emailaddress nvarchar(50) not null,
    t1 nvarchar(50),
    t2 nvarchar(50),
    t3 nvarchar(50),
    t4 nvarchar(50),
    t5 nvarchar(50),
    n1 bigint,
    n2 bigint,
    n3 bigint,
    n4 bigint, 
    n5 bigint,
)