create table Partners (
    syskey bigint not null primary key,
    createddate datetime,
    modifieddate datetime,
    userid nvarchar(50),
    username nvarchar(50),
    recordstatus SMALLINT default 1,
    remark nvarchar(255),
    partnerid bigint IDENTITY(10000001,1),
    partnertype tinyint,
    partnername nvarchar(255),
    address  nvarchar(255),
    contactperson nvarchar(255),
    emailaddress nvarchar(255),
    contactnumber nvarchar(255),
    price decimal(18,2) default 50000,
    t1 nvarchar(50),
    t2 nvarchar(50),
    t3 nvarchar(50),
    t4 nvarchar(50),
    t5 nvarchar(50),
    n1 bigint,
    n2 bigint,
    n3 bigint,
    n4 bigint, 
    n5 bigint,
)


