create table ProformaInvoice (
    syskey bigint not null primary key,
    createddate datetime,
    modifieddate datetime,
    userid nvarchar(50),
    username nvarchar(50),
    recordstatus SMALLINT default 1,
    autokey bigint NOT NULL IDENTITY(1,1),
    Remark nvarchar(255),
    PIRefNumber nvarchar(50),
    Attention nvarchar(50),
    Qty int,
    Price decimal(18, 2),
    Amount decimal(18, 2),
    DiscountAmount decimal(18, 2),
    TaxAmount decimal(18,2),
    Total decimal(18, 2),
    PIDate datetime,
    PaymentDate datetime,
    BUserID nvarchar(50),
    PaymentStatus tinyint,
    BankName nvarchar(255),
    BankRef nvarchar(50),
    Branch nvarchar(50),
    PartnerSysKey bigint,
    paymentref nvarchar(255),
    contact nvarchar(255),
    applicantcount int,
    centerid nvarchar(50),
    approveddate datetime,
    accountnumber text,
    blankstatus int default 0,
    balance int default 0,
    voidcount int default 0,
    t1 nvarchar(255),
    t2 nvarchar(255),
    t3 nvarchar(255),
    t4 nvarchar(255),
    t5 nvarchar(255),
    t6 nvarchar(255),
    t7 nvarchar(255),
    t8 nvarchar(255),
    t9 nvarchar(255),
    t10 nvarchar(255),
    n1 numeric(18, 2),
    n2 numeric(18, 2),
    n3 numeric(18, 2),
    n4 numeric(18, 2), 
    n5 numeric(18, 2),
    n6 numeric(18, 2),
    n7 numeric(18, 2),
    n8 numeric(18, 2),
    n9 numeric(18, 2), 
    n10 numeric(18, 2),
)
CREATE INDEX pi_index
ON [dbo].[ProformaInvoice](pirefnumber);