create table VaccinationRecord (
    syskey bigint not null primary key,
    createddate datetime,
    modifieddate datetime,
    userid nvarchar(50),
    username nvarchar(50),
    recordstatus SMALLINT default 1,
    VaccineLotNo nvarchar(50),
    ApplicationsSysKey bigint not null unique,
    remark nvarchar(255),
    VaccineCompany nvarchar(255),
    PersonName nvarchar(255),
    Vaccination int not null,
    CenterName nvarchar(50),
    CenterSysKey bigint,
    VaccinationDate datetime,
    NextVaccinationDate datetime,
    VaccinationStatus int,
    VaccineSerialNo nvarchar(50),
    cid nvarchar(50),
    t1 nvarchar(255),
    t2 nvarchar(255),
    t3 nvarchar(255),
    t4 nvarchar(255),
    t5 nvarchar(255),
    n1 numeric(18, 2),
    n2 numeric(18, 2),
    n3 numeric(18, 2),
    n4 numeric(18, 2), 
    n5 numeric(18, 2),
)